@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue May 06 19:11:01 +0200 2025
REM SW Build 6060944 on Thu Mar 06 19:10:01 MST 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_top_level_behav -key {Behavioral:sim_1:Functional:tb_top_level} -tclbatch tb_top_level.tcl -view C:/Users/ondra/OneDrive/Dokumenty/GitHub/projekt_v3/tb_stop_behav.wcfg -log simulate.log"
call xsim  tb_top_level_behav -key {Behavioral:sim_1:Functional:tb_top_level} -tclbatch tb_top_level.tcl -view C:/Users/ondra/OneDrive/Dokumenty/GitHub/projekt_v3/tb_stop_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
